#!/bin/sh
 fig2dev -L ps BeH2ene.fig BeH2ene.eps
 fig2dev -L ps BeH2orb.fig BeH2orb.eps
 fig2dev -L ps H2plusLCAO.fig H2plusLCAO.eps
 fig2dev -L ps H2plusLCAO2.fig H2plusLCAO2.eps
 fig2dev -L ps H2plusLCAOener.fig H2plusLCAOener.eps
 fig2dev -L ps H2plusS.fig H2plusS.eps
 fig2dev -L ps antiferromag.fig antiferromag.eps
 fig2dev -L ps atome.fig atome.eps
 fig2dev -L ps boite.fig boite.eps
 fig2dev -L ps chaineosc.fig chaineosc.eps
 fig2dev -L ps champnema.fig champnema.eps
 fig2dev -L ps cholesteric.fig cholesteric.eps
 fig2dev -L ps consp.fig consp.eps
 fig2dev -L ps contrainteavec.fig contrainteavec.eps
 fig2dev -L ps contraintesans.fig contraintesans.eps
 fig2dev -L ps cordef.fig cordef.eps
 fig2dev -L ps cordeg.fig cordeg.eps
 fig2dev -L ps cordevib.fig cordevib.eps
 fig2dev -L ps dirac.fig dirac.eps
 fig2dev -L ps ecran.fig ecran.eps
 fig2dev -L ps emag.fig emag.eps
 fig2dev -L ps eneeleclib.fig eneeleclib.eps
 fig2dev -L ps fermat.fig fermat.eps
 fig2dev -L ps ferromag.fig ferromag.eps
 fig2dev -L ps geodesic.fig geodesic.eps
 fig2dev -L ps glass.fig glass.eps
 fig2dev -L ps hertzprung.fig hertzprung.eps
 fig2dev -L ps huileeau.fig huileeau.eps
 fig2dev -L ps lightdev.fig lightdev.eps
 fig2dev -L ps modesA1.fig modesA1.eps
 fig2dev -L ps modesA1b.fig modesA1b.eps
 fig2dev -L ps modesA1bb.fig modesA1bb.eps
 fig2dev -L ps modesA2.fig modesA2.eps
 fig2dev -L ps modesB1.fig modesB1.eps
 fig2dev -L ps modesB1b.fig modesB1b.eps
 fig2dev -L ps modesB2.fig modesB2.eps
 fig2dev -L ps modesB2b.fig modesB2b.eps
 fig2dev -L ps modesB2bb.fig modesB2bb.eps
 fig2dev -L ps moleceau.fig moleceau.eps
 fig2dev -L ps nematique.fig nematique.eps
 fig2dev -L ps occup.fig occup.eps
 fig2dev -L ps parabe.fig parabe.eps
 fig2dev -L ps paramag.fig paramag.eps
 fig2dev -L ps percol.fig percol.eps
 fig2dev -L ps polar.fig polar.eps
 fig2dev -L ps potperioboit.fig potperioboit.eps
 fig2dev -L ps renorm.fig renorm.eps
 fig2dev -L ps smectiqueA.fig smectiqueA.eps
 fig2dev -L ps smectiqueB.fig smectiqueB.eps
 fig2dev -L ps sommerf.fig sommerf.eps
 fig2dev -L ps spinglass.fig spinglass.eps
 fig2dev -L ps starmass_rad.fig starmass_rad.eps
 fig2dev -L ps symet.fig symet.eps
 fig2dev -L ps tensor.fig tensor.eps
 fig2dev -L ps vanapres.fig vanapres.eps
 fig2dev -L ps vanavant.fig vanavant.eps
 fig2dev -L ps vitnonul.fig vitnonul.eps
 fig2dev -L ps volele.fig volele.eps
